# Generated by Django 4.1.3 on 2022-11-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carniceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Panaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Verduleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Duenio',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
